import type { Metadata } from "next";
import "./globals.css";
import "@/assets/css/custom.css";
import "@/assets/css/responsive.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Compliance Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <body>
            <Header />
        
            {children}

            <Footer />
      </body>
    </html>
  );
}
